
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 20 18:01:01 CDT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORMULARIO = 16;
  public static final int IMAGEN = 8;
  public static final int VINCULO = 10;
  public static final int RPAREN = 6;
  public static final int SEMI = 2;
  public static final int ENCABEZADO = 9;
  public static final int LPAREN = 5;
  public static final int CONTENEDOR = 12;
  public static final int PR = 19;
  public static final int TABLA = 15;
  public static final int COMA = 4;
  public static final int EOF = 0;
  public static final int DIGITO = 18;
  public static final int UNION = 3;
  public static final int TEXTO = 17;
  public static final int error = 1;
  public static final int ESPACIO = 7;
  public static final int FIN = 14;
  public static final int TITULO = 11;
  public static final int ATEXTO = 13;
}

